dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install django
  - pip install django-opentracing
  - pip install wavefront-opentracing-sdk-python
  - pip install flake8 flake8-colors flake8-import-order
  - pip install pep8-naming
  - pip install pydocstyle
  - pip install pylint
before_script:
  - python -m flake8
  - python -m pylint wavefront_django_sdk
  - python -m pydocstyle
script:
  - if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then
      test -n "$(git diff -G version= $TRAVIS_COMMIT_RANGE setup.py)";
    fi
deploy:
  - provider: pypi
    user: wavefront-cs
    server: https://test.pypi.org/legacy/
    password:
      secure: "mm5C+7lnAlHwS1Wd8EIHbGj44qxweHEvyi4PNrhUOSo2Fd04m+EDXZHAXddKZiTdQSl0ZtlA4brlGYrx2CNBvNVKzfyWDnotQsfxlwSGZtvos10DSs1q3wtCAG2AVFBS6zdqza4qgy2GTMB8gdL6/8L1Yfht5nDSZDf6Z95QuoJgXuBTEmGTGIPmctUF/GTky/WXJv2X0appUxRoyypKNVjn3wkquEJIqddmEuH8fSF94qKwo2UNwg2HjCGGk6LiYA7WjoUIipxxpd1eQaHiogvdwUYj1CpvHWi+tENNHh2dmFd/pGRbgxxQ0K7NVLlIErafu41e/5wBaFL2qbfTFYK10B0Nv0F+gYhW/9/mRTS7ourJOWHWt5lOLPzDk9wpMU2U8oxeA5T5sal9MhKCAMWFNpiD8/Z8K0fYQDhTH5Vvh1zA6YSzwDvvZHCjuxzqlIccj1EwMsKnHTED9kbZDMok7rJ6Yv3e3GG9ULzFdgOcP5/Rk4POh36djD25E62emtghCmQE83uQg6iGsOVSCcmkAxnQJ4d/PvhuwpeqSFCjU3T76u70hST82u18Cp5O8DUwF+AyzQFx04Y2YQYsS2w589Mk58Qt6KVV+x+fTecfXfHlLJ33NbOftXFBlJZr5Kod7yM163FfwEOgq+FTqaEsn38Lo/8D+riGnKFjRrE="
    on:
      python: 3.7
  - provider: pypi
    user: wavefront-cs
    password:
      secure: "mm5C+7lnAlHwS1Wd8EIHbGj44qxweHEvyi4PNrhUOSo2Fd04m+EDXZHAXddKZiTdQSl0ZtlA4brlGYrx2CNBvNVKzfyWDnotQsfxlwSGZtvos10DSs1q3wtCAG2AVFBS6zdqza4qgy2GTMB8gdL6/8L1Yfht5nDSZDf6Z95QuoJgXuBTEmGTGIPmctUF/GTky/WXJv2X0appUxRoyypKNVjn3wkquEJIqddmEuH8fSF94qKwo2UNwg2HjCGGk6LiYA7WjoUIipxxpd1eQaHiogvdwUYj1CpvHWi+tENNHh2dmFd/pGRbgxxQ0K7NVLlIErafu41e/5wBaFL2qbfTFYK10B0Nv0F+gYhW/9/mRTS7ourJOWHWt5lOLPzDk9wpMU2U8oxeA5T5sal9MhKCAMWFNpiD8/Z8K0fYQDhTH5Vvh1zA6YSzwDvvZHCjuxzqlIccj1EwMsKnHTED9kbZDMok7rJ6Yv3e3GG9ULzFdgOcP5/Rk4POh36djD25E62emtghCmQE83uQg6iGsOVSCcmkAxnQJ4d/PvhuwpeqSFCjU3T76u70hST82u18Cp5O8DUwF+AyzQFx04Y2YQYsS2w589Mk58Qt6KVV+x+fTecfXfHlLJ33NbOftXFBlJZr5Kod7yM163FfwEOgq+FTqaEsn38Lo/8D+riGnKFjRrE="
    on:
      python: 3.7
      tags: true
