name: Python Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 flake8-colors flake8-import-order
        pip install pep8-naming pydocstyle pylint

    - name: Flake8 
      run: python -m flake8

    - name: Pylint
      run: python -m pylint wavefront_django_sdk

    - name: Pydocstyle
      run: python -m pydocstyle

    - name: Check if version is updated
      run: test -n "$(git diff -G version= origin/master HEAD setup.py)"